// <auto-generated />
using System;
using GeradorCertificados.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeradorCertificados.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(AplicacaoDbContext))]
    [Migration("20260922120311_AdicionarModuloCertificados")]
    partial class AdicionarModuloCertificados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeradorCertificados.Domain.Certificados.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DataGeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("Certificados", (string)null);
                });

            modelBuilder.Entity("GeradorCertificados.Domain.Certificados.SolicitacaoCertificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pendente', 'GerandoCertificados', 'GerandoZip')");

                    b.ToTable("SolicitacoesCertificado", (string)null);
                });

            modelBuilder.Entity("GeradorCertificados.Domain.Cursos.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("GeradorCertificados.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GeradorCertificados.Domain.Certificados.Certificado", b =>
                {
                    b.HasOne("GeradorCertificados.Domain.Certificados.SolicitacaoCertificado", null)
                        .WithMany("Certificados")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeradorCertificados.Domain.Certificados.SolicitacaoCertificado", b =>
                {
                    b.HasOne("GeradorCertificados.Domain.Cursos.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeradorCertificados.Domain.Certificados.SolicitacaoCertificado", b =>
                {
                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
